# Generated by Django 3.1.7 on 2021-03-16 16:18

from django.db import migrations, models
import drf_recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='', upload_to=drf_recipes.models.recipe_image_file_path),
        ),
    ]
