# Generated by Django 3.1.7 on 2021-03-16 17:14

from django.db import migrations, models
import drf_recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_recipes', '0002_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='E:\\pythonProject\\DRF1\\static_cdn\\media_root\\default.jpeg', upload_to=drf_recipes.models.recipe_image_file_path),
        ),
    ]
